apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-infrastructure-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-infrastructure-repo
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd-github-infrastructure-repo
        property: sshPrivateKey
