{{- if .Values.featureBranchEnv.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-downloader-secret
  namespace: {{ .Release.Namespace }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: Auto
        key: backup-downloader-secret
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-cluster-secret-store-dev
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: backup-downloader-secret
{{- end -}}
