{{- if .Values.rabbitmq.virtualHost.create -}}
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ .Values.environment }}
  namespace: rabbitmq-system
spec:
  name: {{ .Values.environment }} # vhost name; required and cannot be updated
  rabbitmqClusterReference:
    name: madkhol # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: madkhol-{{ .Values.environment }}
  namespace: rabbitmq-system
spec:
  vhost: "{{ .Values.environment }}"
  user: madkhol-service
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: madkhol
{{- end -}}
