{{- if .Values.secrets -}}
{{- $fullName := include "service.fullname" . -}}
{{- range $key, $value := .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-{{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: "30m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.externalSecretVaultName }}
  target:
    name: {{ $fullName }}-{{ $key }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $key }}
      decodingStrategy: Auto
{{- end }}
{{- end }}
